### PR TITLE
Add cache support #376

### LINKED ISSUE #376: Support DataSet cache operations
It would be nice for the DataSet to support the Spark cache operations to support this use-case:

`cached_ds: DataSet[A] = original_ds.cache()`

These cache operations return a PySpark DataFrame:
* DataFrame.cache()
* DataFrame.persist()
* DataFrame.unpersist()

### PR DESCRIPTION
**Pull request by jonmclean**
This pull request adds support for cache operations to the DataSet object.

Fixes #376

### CODE REVIEW

**Comment by jonmclean** [comment]
If possible I would like to backport this to a version that supports Spark 3.4 as well.  My current project is on Spark 3.4 because the infrastructure it runs on does not support 3.5 yet.

The code changes in this PR should work on Spark 3.4 and prior versions without modifications.

I would appreciate advice on how the project maintainers would prefer the backport to be done.

**Comment by nanne-aben** [comment]
Thanks @jonmcleaJo, this is a really useful contribution!

Wrt backporting, it should already work with spark 3.4 out of the box. We don't really explicitly test older versions of spark in the cicd because we don't expect any trouble there. Of course, if you do see a reason why we'd need to do so, we can easily add that. Let me know what you think!

Happy to merge this btw!

**Review by nanne-aben — APPROVED** [review]

**Comment by jonmclean** [comment]
Let's go ahead and merge.  I reviewed the changes over the last few releases and there does not appear to be anything specific to Spark 3.5.

**Comment by nanne-aben** [comment]
Thank you for your contribution!

**Pull request merged**
